char poem[]= "U lukomor'ya dub zelenyj,\n"
             "Zlataya cep' na dube tom:\n"
             "I dnem i noch'yu kot uchenyj\n"
             "Vsyo hodit po cepi krugom;\n"
             "Idet napravo — pesn' zavodit,\n"
             "Nalevo — skazku govorit.\n"
             "Tam chudesa: tam leshij brodit,\n"
             "Rusalka na vetvyah sidit;\n"
             "Tam na nevedomyh dorozhkah\n"
             "Sledy nevidannyh zverej;\n"
             "Izbushka tam na kur'ih nozhkah\n"
             "Stoit bez okon, bez dverej;\n"
             "Tam les i dol videnij polny;\n"
             "Tam o zare prihlynut volny\n"
             "Na breg peschanyj i pustoj,\n"
             "I tridcat' vityazej prekrasnyh;\n"
             "CHredoj iz vod vyhodyat yasnyh,\n"
             "I s nimi dyad'ka ih morskoj;\n"
             "Tam korolevich mimohodom\n"
             "Plenyaet groznogo carya;\n"
             "Tam v oblakah pered narodom\n"
             "CHerez lesa, cherez morya\n"
             "Koldun neset bogatyrya;\n"
             "V temnice tam carevna tuzhit,\n"
             "A buryj volk ej verno sluzhit;\n"
             "Tam stupa s Baboyu YAgoj\n"
             "Idet, bredet sama soboj;\n"
             "Tam car' Kashchej nad zlatom chahnet;\n"
             "Tam russkoj duh… tam Rus'yu pahnet!\n"
             "I tam ya byl, i med ya pil;\n"
             "U morya videl dub zelenyj;\n"
             "Pod nim sidel, i kot uchenyj\n"
             "Svoi mne skazki govoril.\n"
             "Odnu ya pomnyu: skazku etu\n"
             "Povedayu teper' ya svetu…\n"
             "Dela davno minuvshih dnej,\n"
             "Predan'ya stariny glubokoj.\n"
             "V tolpe moguchih synovej,\n"
             "S druz'yami, v gridnice vysokoj\n"
             "Vladimir-solnce piroval;\n"
             "Men'shuyu doch' on vydaval\n"
             "Za knyazya hrabrogo Ruslana\n"
             "I med iz tyazhkogo stakana\n"
             "Za ih zdorov'e vypival.\n"
             "Ne skoro eli predki nashi,\n"
             "Ne skoro dvigalis' krugom\n"
             "Kovshi, serebryanye chashi\n"
             "S kipyashchim pivom i vinom.\n"
             "Oni vesel'e v serdce lili,\n"
             "SHipela pena po krayam,\n"
             "Ih vazhno chashniki nosili\n"
             "I nizko klanyalis' gostyam.\n"
             "Slilisya rechi v shum nevnyatnyj;\n"
             "ZHuzhzhit gostej veselyj krug;\n"
             "No vdrug razdalsya glas priyatnyj\n"
             "I zvonkih guslej beglyj zvuk;\n"
             "Vse smolkli, slushayut Bayana:\n"
             "I slavit sladostnyj pevec\n"
             "Lyudmilu-prelest', i Ruslana,\n"
             "I Lelem svityj im venec.\n"
             "No, strast'yu pylkoj utomlennyj,\n"
             "Ne est, ne p'et Ruslan vlyublennyj;\n"
             "Na druga milogo glyadit,\n"
             "Vzdyhaet, serditsya, gorit\n"
             "I, shchiplya us ot neterpen'ya,\n"
             "Schitaet kazhdye mgnoven'ya.\n"
             "V unyn'i, s pasmurnym chelom,\n"
             "Za shumnym, svadebnym stolom\n"
             "Sidyat tri vityazya mladye;\n"
             "Bezmolvny, za kovshom pustym,\n"
             "Zabyli kubki krugovye,\n"
             "I brashna nepriyatny im;\n"
             "Ne slyshat veshchego Bayana;\n"
             "Potupili smushchennyj vzglyad:\n"
             "To tri sopernika Ruslana;\n"
             "V dushe neschastnye tayat\n"
             "Lyubvi i nenavisti yad.\n"
             "Odin — Rogdaj, voitel' smelyj,\n"
             "Mechom razdvinuvshij predely\n"
             "Bogatyh kievskih polej;\n"
             "Drugoj — Farlaf, krikun nadmennyj,\n"
             "V pirah nikem ne pobezhdennyj,\n"
             "No voin skromnyj sred' mechej;\n"
             "Poslednij, polnyj strastnoj dumy,\n"
             "Mladoj hazarskij han Ratmir:\n"
             "Vse troe bledny i ugryumy,\n"
             "I pir veselyj im ne v pir.\n"
             "Vot konchen on; vstayut ryadami,\n"
             "Smeshalis' shumnymi tolpami,\n"
             "I vse glyadyat na molodyh:\n"
             "Nevesta ochi opustila,\n"
             "Kak budto serdcem priunyla,\n"
             "I svetel radostnyj zhenih.\n"
             "No ten' ob'emlet vsyu prirodu,\n"
             "Uzh blizko k polnochi gluhoj;\n"
             "Boyare, zadremav ot medu,\n"
             "S poklonom ubralis' domoj.\n"
             "ZHenih v vostorge, v upoen'e:\n"
             "Laskaet on v voobrazhen'e\n"
             "Stydlivoj devy krasotu;\n"
             "No s tajnym, grustnym umilen'em\n"
             "Velikij knyaz' blagosloven'em\n"
             "Daruet yunuyu chetu.\n"
             "I vot nevestu moloduyu\n"
             "Vedut na brachnuyu postel';\n"
             "Ogni pogasli… i nochnuyu\n"
             "Lampadu zazhigaet Lel'.\n"
             "Svershilis' milye nadezhdy,\n"
             "Lyubvi gotovyatsya dary;\n"
             "Padut revnivye odezhdy\n"
             "Na caregradskie kovry…\n"
             "Vy slyshite l' vlyublennyj shepot,\n"
             "I poceluev sladkij zvuk,\n"
             "I preryvayushchijsya ropot\n"
             "Poslednej robosti?.. Suprug\n"
             "Vostorgi chuvstvuet zarane;\n"
             "I vot oni nastali… Vdrug\n"
             "Grom gryanul, svet blesnul v tumane,\n"
             "Lampada gasnet, dym bezhit,\n"
             "Krugom vsyo smerklos', vsyo drozhit,\n"
             "I zamerla dusha v Ruslane…\n"
             "Vsyo smolklo. V groznoj tishine\n"
             "Razdalsya dvazhdy golos strannyj,\n"
             "I kto-to v dymnoj glubine\n"
             "Vzvilsya chernee mgly tumannoj…\n"
             "I snova terem pust i tih;\n"
             "Vstaet ispugannyj zhenih,\n"
             "S lica katitsya pot ostylyj;\n"
             "Trepeshcha, hladnoyu rukoj\n"
             "On voproshaet mrak nemoj…\n"
             "O gore: net podrugi miloj!\n"
             "Hvataet vozduh on pustoj;\n"
             "Lyudmily net vo t'me gustoj,\n"
             "Pohishchena bezvestnoj siloj.\n"
             "Ah, esli muchenik lyubvi\n"
             "Stradaet strast'yu beznadezhno;\n"
             "Hot' grustno zhit', druz'ya moi,\n"
             "Odnako zhit' eshche vozmozhno.\n"
             "No posle dolgih, dolgih let\n"
             "Obnyat' vlyublennuyu podrugu,\n"
             "ZHelanij, slez, toski predmet,\n"
             "I vdrug minutnuyu suprugu\n"
             "Navek utratit'… o druz'ya,\n"
             "Konechno luchshe b umer ya!\n"
             "Odnako zhiv Ruslan neschastnyj.\n"
             "No chto skazal velikij knyaz'?\n"
             "Srazhennyj vdrug molvoj uzhasnoj,\n"
             "Na zyatya gnevom raspalyas',\n"
             "Ego i dvor on sozyvaet:\n"
             "«Gde, gde Lyudmila?» — voproshaet\n"
             "S uzhasnym, plamennym chelom.\n"
             "Ruslan ne slyshit. «Deti, drugi!\n"
             "YA pomnyu prezhnie zaslugi:\n"
             "O szhal'tes' vy nad starikom\n";
